[package]
name = "proxy_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
threadpool = "1.8.1"
ua_generator = "0.3.5"
ureq = { version = "2.7.1", features = ["socks-proxy"] }
